FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

# Generate Prisma Client
RUN npx prisma generate

# Build the worker typescript code
RUN npm run build:worker

ENV NODE_ENV production

# Run the compiled javascript worker
CMD ["node", "dist/workers/index.js"]
