import type { Metadata, Viewport } from "next";
import { Inter, Plus_Jakarta_Sans, JetBrains_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { UIProvider } from "../components/layout/UIContext";
import { AdsterraSitewide } from "../components/ads/AdsterraSitewide";


const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-sans",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://lusthub.web.id"),
  title: {
    default: "LustHub — Free HD Porn Videos",
    template: "%s — LustHub",
  },
  description: "LustHub is a fast, free, and modern HD porn video platform. Watch thousands of premium adult videos instantly in high quality.",
  openGraph: {
    title: "LustHub — Free HD Porn Videos",
    description: "LustHub is a fast, free, and modern HD porn video platform. Watch thousands of premium adult videos instantly in high quality.",
    type: "website",
    locale: "en_US",
    siteName: "LustHub",
    url: "https://lusthub.web.id",
    images: [
      {
        // Generated by app/opengraph-image.tsx — served at /opengraph-image
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "LustHub — Free HD Porn Videos",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "LustHub — Free HD Porn Videos",
    description: "Watch thousands of premium adult videos instantly in high quality on LustHub.",
    images: ["/opengraph-image"],
  },
  verification: {
    google: "G71CC4n1uaSgqVnjIvv3JSKs78kXb2lYNn_yJXiEb7Q",
  },
};


export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} ${plusJakartaSans.variable} ${jetbrainsMono.variable} min-h-screen bg-[#0F0F0F] text-[#F1F1F1] antialiased font-sans`}>
        <UIProvider>
          {children}
        </UIProvider>

        {/* ── Adsterra Sitewide Ads ──────────────────────────────────────────
            Loads Popunder + Social Bar once per session across all pages.
            strategy="afterInteractive" ensures LCP is never blocked.
        ─────────────────────────────────────────────────────────────────── */}
        <AdsterraSitewide />

        {/*
          ── Plausible Analytics ────────────────────────────────────────────
          Privacy-first, cookieless analytics.
          - strategy="afterInteractive" → loads after LCP, never blocks paint
          - SPA navigation is tracked automatically (Next.js pushState aware)
          - No cookies, no PII, no consent banner required
          - To activate: sign up at plausible.io and add lusthub.web.id
          ─────────────────────────────────────────────────────────────────── */}
        <Script
          src="https://plausible.io/js/script.js"
          data-domain="lusthub.web.id"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
