import { notFound } from "next/navigation";
import { Metadata } from "next";
import Link from "next/link";
import { ChevronLeft, ChevronRight, LayoutGrid } from "lucide-react";
import { EpornerAPI } from "@/lib/api/eporner";
import { VideoGrid } from "@/components/video/VideoGrid";
import { getCategoryBySlug, TIER1_CATEGORIES } from "@/lib/category-config";
import { AdsterraBanner } from "@/components/ads/AdsterraBanner";

const SITE_URL = process.env.NEXT_PUBLIC_APP_URL || "https://lusthub.web.id";

// ISR: regenerate category pages every hour in the background.
// New videos synced by the worker will appear within 60 minutes — no redeploy needed.
// Safe for ISR: no user-specific data, stable canonical URLs.
export const revalidate = 3600;

const PER_PAGE = 30;

// ─── Metadata ────────────────────────────────────────────────────────────────

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const cat = getCategoryBySlug(slug);
  if (!cat) return { title: "Category Not Found" };

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://lusthub.web.id";

  return {
    title: cat.title,
    description: cat.description,
    openGraph: {
      title: `${cat.title} — LustHub`,
      description: cat.description,
      type: "website",
      url: `${baseUrl}/category/${cat.slug}`,
      siteName: "LustHub",
      images: [
        {
          // Self-hosted branded image — generated by category/opengraph-image.tsx
          url: `${baseUrl}/category/${cat.slug}/opengraph-image`,
          width: 1200,
          height: 630,
          alt: `${cat.title} — LustHub`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `${cat.title} — LustHub`,
      description: cat.description,
      images: [
        `${baseUrl}/category/${cat.slug}/opengraph-image`,
      ],
    },
    alternates: {
      canonical: `${baseUrl}/category/${cat.slug}`,
    },
  };
}

// ─── Static params for the 15 Tier-1 categories ──────────────────────────────
// Pre-generates the route list at build time so Next.js knows these slugs exist.
// Unknown slugs still render dynamically (notFound() is called).

export function generateStaticParams() {
  return TIER1_CATEGORIES.map((cat) => ({ slug: cat.slug }));
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default async function CategoryPage({
  params,
  searchParams,
}: {
  params: Promise<{ slug: string }>;
  searchParams: Promise<{ page?: string }>;
}) {
  const { slug } = await params;
  const resolvedSearchParams = await searchParams;

  // Reject unknown slugs immediately — keeps non-Tier-1 pages from going live
  const cat = getCategoryBySlug(slug);
  if (!cat) return notFound();

  const page = Math.max(1, parseInt(resolvedSearchParams.page || "1", 10));

  // Fetch videos from Eporner using the category display name as the search query
  const res = await EpornerAPI.search({
    query: cat.name,
    page,
    per_page: PER_PAGE,
    order: "latest",
  });

  const videos = res?.videos || [];
  const totalPages = res?.total_pages || 1;

  // Soft-404 guard: if a paginated request returns no videos and is beyond page 1,
  // return a proper 404 instead of rendering an empty grid.
  // An empty paginated page is a soft-404 risk — Google flags it as low-value content.
  // Page 1 with zero results is intentionally allowed (category exists but may be sparse).
  if (page > 1 && videos.length === 0) {
    return notFound();
  }

  // Clamp page to valid range — prevents rendering "Page 50 of 3" style confusion
  if (page > totalPages && totalPages > 0) {
    return notFound();
  }

  // Related categories for internal linking (exclude self)
  const relatedCats = cat.related
    .map((rSlug) => TIER1_CATEGORIES.find((c) => c.slug === rSlug))
    .filter(Boolean) as (typeof TIER1_CATEGORIES)[number][];

  // Pagination URL builder
  const getPageUrl = (targetPage: number) => {
    const params = new URLSearchParams();
    if (targetPage > 1) params.set("page", String(targetPage));
    const qs = params.toString();
    return `/category/${slug}${qs ? `?${qs}` : ""}`;
  };

  // ── JSON-LD ───────────────────────────────────────────────────────────────
  // BreadcrumbList mirrors the visible breadcrumb nav exactly — no content mismatch.
  // CollectionPage accurately describes this as a curated video collection.
  const categoryUrl = `${SITE_URL}/category/${cat.slug}`;
  const categoryJsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "CollectionPage",
        "@id": `${categoryUrl}/#collectionpage`,
        "name": cat.title,
        "description": cat.description,
        "url": categoryUrl,
        "breadcrumb": { "@id": `${categoryUrl}/#breadcrumb` },
        "isPartOf": { "@id": `${SITE_URL}/#website` },
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${categoryUrl}/#breadcrumb`,
        "itemListElement": [
          {
            "@type": "ListItem",
            "position": 1,
            "name": "Home",
            "item": SITE_URL,
          },
          {
            "@type": "ListItem",
            "position": 2,
            "name": "Categories",
            "item": `${SITE_URL}/categories`,
          },
          {
            "@type": "ListItem",
            "position": 3,
            "name": cat.name,
            "item": categoryUrl,
          },
        ],
      },
    ],
  };

  return (
    <>
      {/* Category JSON-LD — server-side, injected before page content */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(categoryJsonLd) }}
      />

      <div className="container mx-auto max-w-7xl px-4 py-6 space-y-8">

      {/* ── Page Header ─────────────────────────────────────────── */}
      <div className="border-b border-white/5 pb-5">
        {/* Breadcrumb */}
        <nav aria-label="Breadcrumb" className="flex items-center gap-1.5 text-[10px] text-muted-foreground font-mono mb-3">
          <Link href="/" className="hover:text-white transition-colors">Home</Link>
          <span>/</span>
          <Link href="/categories" className="hover:text-white transition-colors">Categories</Link>
          <span>/</span>
          <span className="text-white">{cat.name}</span>
        </nav>

        {/* H1 — critical for SEO, visible in initial HTML */}
        <h1 className="text-2xl md:text-3xl font-extrabold text-white flex items-center gap-3 font-heading">
          <LayoutGrid className="h-6 w-6 text-red-500 shrink-0" />
          {cat.title}
        </h1>

        {/* Intro text — unique per category, server-rendered, no JS required */}
        <p className="text-sm text-foreground/70 mt-3 leading-relaxed max-w-3xl">
          {cat.intro}
        </p>

        {/* Video count */}
        {res?.total_count != null && (
          <p className="text-[11px] text-muted-foreground font-mono mt-2">
            {res.total_count.toLocaleString("en-US")} videos found
          </p>
        )}
      </div>

      {/* ── Related Categories — internal links, server-rendered ── */}
      {relatedCats.length > 0 && (
        <div>
          <h2 className="text-xs font-bold text-muted-foreground uppercase tracking-widest font-mono mb-3">
            Related Categories
          </h2>
          <div className="flex flex-wrap gap-2">
            {relatedCats.map((related) => (
              <Link
                key={related.slug}
                href={`/category/${related.slug}`}
                className="px-3 py-1.5 rounded-full bg-[#1F1F1F] border border-white/10 text-xs text-[#CCCCCC] hover:text-white hover:bg-[#2A2A2A] hover:border-white/20 transition-all font-medium"
              >
                {related.name}
              </Link>
            ))}
            <Link
              href="/categories"
              className="px-3 py-1.5 rounded-full bg-red-600/10 border border-red-600/20 text-xs text-red-400 hover:text-red-300 hover:bg-red-600/20 transition-all font-medium"
            >
              All Categories →
            </Link>
          </div>
        </div>
      )}

      {/* ── Adsterra Banner ─────────────────────────────────────
           Leaderboard 728×90 — desktop & tablet
           Mobile Banner 320×50 — mobile only
           Placed above video grid for maximum viewability.
      ────────────────────────────────────────────────────────── */}
      <AdsterraBanner
        adKey="361158242f9f7ba4b97dddf961d303d6"
        width={728}
        height={90}
        className="hidden lg:flex my-2"
      />
      <AdsterraBanner
        adKey="1657e4fb76c1445cfbb411b5b0a859ee"
        width={320}
        height={50}
        className="flex lg:hidden my-2"
      />

      {/* ── Video Grid — Server Component renders initial HTML ──── */}
      <VideoGrid videos={videos} />

      {/* ── Adsterra Banner (below grid) ────────────────────────────
           Medium Rectangle 300x250
           Placed below video grid for post-scroll viewability.
      ────────────────────────────────────────────────────────── */}
      <AdsterraBanner
        adKey="3f7aeb74bde61edc8e369b2303797899"
        width={300}
        height={250}
        className="flex my-4"
      />

      {/* ── Pagination — clean path-based links ─────────────────── */}
      {totalPages > 1 && (
        <div className="flex justify-center items-center gap-2 pt-6 pb-12 font-semibold">
          {page > 1 ? (
            <Link
              href={getPageUrl(page - 1)}
              className="flex items-center gap-1 px-4 py-2 rounded-lg bg-[#272727] hover:bg-[#3F3F3F] text-xs transition-colors text-white cursor-pointer border border-white/5"
            >
              <ChevronLeft className="h-4 w-4" />
              <span>Previous</span>
            </Link>
          ) : (
            <button
              disabled
              className="flex items-center gap-1 px-4 py-2 rounded-lg bg-[#1F1F1F] text-xs text-muted-foreground opacity-30 cursor-not-allowed border border-white/5"
            >
              <ChevronLeft className="h-4 w-4" />
              <span>Previous</span>
            </button>
          )}

          <span className="text-xs text-[#AAAAAA] px-4 font-mono">
            Page <span className="text-white font-bold">{page}</span> of{" "}
            <span className="text-white font-bold">{totalPages}</span>
          </span>

          {page < totalPages ? (
            <Link
              href={getPageUrl(page + 1)}
              className="flex items-center gap-1 px-4 py-2 rounded-lg bg-[#272727] hover:bg-[#3F3F3F] text-xs transition-colors text-white cursor-pointer border border-white/5"
            >
              <span>Next</span>
              <ChevronRight className="h-4 w-4" />
            </Link>
          ) : (
            <button
              disabled
              className="flex items-center gap-1 px-4 py-2 rounded-lg bg-[#1F1F1F] text-xs text-muted-foreground opacity-30 cursor-not-allowed border border-white/5"
            >
              <span>Next</span>
              <ChevronRight className="h-4 w-4" />
            </button>
          )}
        </div>
      )}
    </div>
    </>
  );
}
